version: "3.7"

services:
  mongodb-0:
    hostname: mongodb-0.shopgrip.ru
    container_name: mongodb-0
    image: mongo:4.4
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ~/volumes/mongodb-0/data:/data
    command: "mongod --bind_ip_all --replSet=rs0"
