apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stan-pvc
spec:
  storageClassName: do-block-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: streaming.nats.io/v1alpha1
kind: NatsStreamingCluster
metadata:
  name: stan
spec:
  size: 1
  natsSvc: nats
  config:
    storeDir: /stan
    ftGroup: stan
  template:
    spec:
      volumes:
        - name: stan-volume
          persistentVolumeClaim:
            claimName: stan-pvc
      containers:
        - name: nats-streaming
          args:
            - "--store"
            - "FILE"
            - "--max_msgs"
            - "0"
            - "--max_bytes"
            - "1073741824"
            - "--max_age"
            - "720h"
            - "--http_port"
            - "8222"
          volumeMounts:
            - name: stan-volume
              mountPath: /stan
