apiVersion: v1
kind: ConfigMap
metadata:
  name: redis
  namespace: leaq
data:
  redis.conf: |+
    appendonly yes
    protected-mode no
    maxmemory 250mb

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: leaq
spec:
  serviceName: redis
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:6.0-alpine
          ports:
            - containerPort: 6379
              name: client
          command:
            - "redis-server"
            - "/conf/redis.conf"
          resources:
            requests:
              cpu: 100m
              memory: 25Mi
            limits:
              cpu: "1"
              memory: 1Gi
          volumeMounts:
            - name: conf
              mountPath: /conf
              readOnly: false
      volumes:
        - name: conf
          configMap:
            name: redis
            defaultMode: 0755
