apiVersion: v1
kind: Service
metadata:
  name: stan
  namespace: leaq
  labels:
    app: stan
spec:
  ports:
    - port: 4222
      name: client
    - port: 8222
      name: monitoring
  clusterIP: None
  selector:
    app: stan
