version: "3.7"

services:
  mongodb:
    hostname: mongodb
    container_name: mongodb
    image: mongo:4.4
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ~/volumes/mongodb/data:/data
