apiVersion: v1
kind: Service
metadata:
  name: memcached
  namespace: ingress-nginx
  labels:
    app: memcached
spec:
  ports:
    - port: 11211
      name: client
  clusterIP: None
  selector:
    app: memcached
