apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: memcached
  namespace: ingress-nginx
spec:
  serviceName: memcached
  replicas: 1
  selector:
    matchLabels:
      app: memcached
  template:
    metadata:
      labels:
        app: memcached
    spec:
      containers:
        - name: memcached
          image: memcached
          command:
            - memcached
            - -vv
          ports:
            - containerPort: 11211
              name: client
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              cpu: "1"
              memory: 1Gi
