name: master

on:
  push:
    branches:
      - master

jobs:
  apply_infra:
    name: Apply infra
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_CI_TOKEN }}

      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save k8s

      - name: Apply all resources
        run: kubectl -n leaq apply -f ${{ github.workspace }}/k8s_resources
